// Copyright 2024 Arthur Sonzogni. All rights reserved.
// Use of this source code is governed by the MIT license that can be found in
// the LICENSE file.
#ifndef RTXUI_DEFAULT_COMPONENTS_INTERNAL_HPP_
#define RTXUI_DEFAULT_COMPONENTS_INTERNAL_HPP_

#include "rtxui/component/component_internal.hpp"
#include "rtxui/component/default/a/a.hpp"
#include "rtxui/component/default/b/b.hpp"
#include "rtxui/component/default/blockquote/blockquote.hpp"
#include "rtxui/component/default/button/button.hpp"
#include "rtxui/component/default/checkbox/checkbox.hpp"
#include "rtxui/component/default/code/code.hpp"
#include "rtxui/component/default/details/details.hpp"
#include "rtxui/component/default/dialog/dialog.hpp"
#include "rtxui/component/default/div/div.hpp"
#include "rtxui/component/default/fieldset/fieldset.hpp"
#include "rtxui/component/default/h1/h1.hpp"
#include "rtxui/component/default/hr/hr.hpp"
#include "rtxui/component/default/i/i.hpp"
#include "rtxui/component/default/input/input.hpp"
#include "rtxui/component/default/kbd/kbd.hpp"
#include "rtxui/component/default/label/label.hpp"
#include "rtxui/component/default/legend/legend.hpp"
#include "rtxui/component/default/li/li.hpp"
#include "rtxui/component/default/markdown/markdown.hpp"
#include "rtxui/component/default/ol/ol.hpp"
#include "rtxui/component/default/option/option.hpp"
#include "rtxui/component/default/p/p.hpp"
#include "rtxui/component/default/pre/pre.hpp"
#include "rtxui/component/default/progress/progress.hpp"
#include "rtxui/component/default/radio/radio.hpp"
#include "rtxui/component/default/s/s.hpp"
#include "rtxui/component/default/select/select.hpp"
#include "rtxui/component/default/semantic/semantic.hpp"
#include "rtxui/component/default/slider/slider.hpp"
#include "rtxui/component/default/span/span.hpp"
#include "rtxui/component/default/strong/strong.hpp"
#include "rtxui/component/default/summary/summary.hpp"
#include "rtxui/component/default/tab_pane/tab_pane.hpp"
#include "rtxui/component/default/tabs/tabs.hpp"
#include "rtxui/component/default/textarea/textarea.hpp"
#include "rtxui/component/default/tooltip/tooltip.hpp"
#include "rtxui/component/default/u/u.hpp"
#include "rtxui/component/default/ul/ul.hpp"

#endif  // RTXUI_DEFAULT_COMPONENTS_INTERNAL_HPP_
