#ifndef RTXUI_COMPONENTS_HPP
#define RTXUI_COMPONENTS_HPP

#include "component/component.hpp"

namespace rtxui {

RTXUI_COMPONENT_DECLARE(div);
RTXUI_COMPONENT_DECLARE(span);
RTXUI_COMPONENT_DECLARE(p);
RTXUI_COMPONENT_DECLARE(strong);
RTXUI_COMPONENT_DECLARE(ul);
RTXUI_COMPONENT_DECLARE(li);
RTXUI_COMPONENT_DECLARE(ol);
RTXUI_COMPONENT_DECLARE(button);

}  // namespace rtxui

#endif  // RTXUI_COMPONENTS_HPP
