cc_library(
  name = "xml",
  hdrs = [
    "xml.hpp"
  ],
  srcs = [
    "xml.cpp"
  ] ,
  deps = [
    ":expected"
  ],
  visibility = ["//visibility:public"],
)

cc_library(
  name = "task",
  hdrs = [
    "task.hpp",
    "task_queue.hpp",
    "task_runner.hpp",
  ],
  srcs = [
    "task.cpp",
    "task_queue.cpp",
    "task_runner.cpp",
  ],
  visibility = ["//visibility:public"],
)

cc_library(
  name = "reactive",
  hdrs = [
    "reactive.hpp",
  ],
  srcs = [
    "reactive.cpp",
  ],
  visibility = ["//visibility:public"],
)

cc_test(
  name = "test",
  srcs = [
    "xml_test.cpp",
    "task_test.cpp",
    "reactive_test.cpp",
  ],
  deps = [
    ":xml",
    ":task",
    ":reactive",
    "@catch2//:catch2_main",
  ],
)

cc_library(
  name = "expected",
  hdrs = [
    "expected.hpp",
  ],
  visibility = ["//visibility:public"],
)
